### ISSUE TITLE
port number

### ISSUE THREAD

**Issue by osazemeu** [karlkori/dockerized-angular-app#1]
I am completely new to dockerizing angular 2, and its messing me up. Thanks for this app. What should be my port based on this sample app? `localhost:5000` or `localhost:4200`?

**Comment by karlkori** [comment]
Take a look at the following line: https://github.com/karlkori/dockerized-angular-app/blob/master/Dockerfile#L32
at that line you said Docker to expose your angular app on 5000 port - localhost:5000

**Comment by karlkori** [comment]
but if you use the next command to run Docker container: 
`docker run -it -p 80:5000 dockerized-angular-app`
your app will be available on port 80, just use http://localhost on your browser
